/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewsteste;

import dao.Banco;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author vini
 */
public class Configuracao extends javax.swing.JPanel {

    
     Banco ba = new Banco();
    String sen;
    int flag = 0;

    /**
     * Creates new form Configuracao
     */
    public Configuracao() {
        initComponents();
    }
    
    public boolean valida() {

        if ("".equals(txt_nome2.getText())) {
            JOptionPane.showMessageDialog(null, "Preenche o campo nome");
            return false;
        }
        if ("".equals(txt_login2.getText())) {
            JOptionPane.showMessageDialog(null, "Preenche o campo login");
            return false;
        }
        if ("".equals(txt_senha2.getText()) && flag == 1) {
            JOptionPane.showMessageDialog(null, "Preenche o campo senha");
            return false;
        }
        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txt_BuscaLogin2 = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        txt_login2 = new javax.swing.JTextField();
        txt_nome2 = new javax.swing.JTextField();
        txt_senha2 = new javax.swing.JPasswordField();
        txt_senhaAtual2 = new javax.swing.JPasswordField();
        manterSenha3 = new javax.swing.JCheckBox();
        jLabel51 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        CodFuncionario = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txt_NovaSenha2 = new javax.swing.JPasswordField();
        jLabel56 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        checkPerAgenda = new javax.swing.JCheckBox();
        checkPerProprietario = new javax.swing.JCheckBox();
        checkPerAnimal = new javax.swing.JCheckBox();
        checkPerServico = new javax.swing.JCheckBox();
        checkPerEstoque = new javax.swing.JCheckBox();
        checkPerVenda = new javax.swing.JCheckBox();
        checkPerFinanceiro = new javax.swing.JCheckBox();
        checkPerProdutos = new javax.swing.JCheckBox();
        jSeparator11 = new javax.swing.JSeparator();
        checkPerHistoricos = new javax.swing.JCheckBox();
        checkPerAltera = new javax.swing.JCheckBox();
        checkPerExclui = new javax.swing.JCheckBox();

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Configurações");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(261, 1, 87, 15);

        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backup.png"))); // NOI18N
        btnBackup.setText("Realizar Backup");
        btnBackup.setToolTipText("");
        btnBackup.setPreferredSize(new java.awt.Dimension(100, 35));
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        jPanel6.add(btnBackup);
        btnBackup.setBounds(484, 456, 140, 35);

        jTextField16.setText("C:\\Users\\Rafael\\Documentos/SysVet");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField16);
        jTextField16.setBounds(170, 458, 301, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Diretório Backup:");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(53, 466, 97, 14);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));
        jPanel9.setLayout(null);

        txt_BuscaLogin2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(txt_BuscaLogin2);
        txt_BuscaLogin2.setBounds(30, 50, 180, 20);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apply.png"))); // NOI18N
        btnAlterar.setText("Salvar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnAlterar);
        btnAlterar.setBounds(480, 340, 100, 30);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Login");
        jPanel9.add(jLabel50);
        jLabel50.setBounds(30, 30, 90, 20);

        txt_login2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_login2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_login2txt_loginMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_login2txt_loginMouseReleased(evt);
            }
        });
        txt_login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login2txt_loginActionPerformed(evt);
            }
        });
        jPanel9.add(txt_login2);
        txt_login2.setBounds(20, 210, 210, 20);

        txt_nome2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(txt_nome2);
        txt_nome2.setBounds(70, 170, 380, 20);

        txt_senha2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_senha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senha2txt_senhaActionPerformed(evt);
            }
        });
        jPanel9.add(txt_senha2);
        txt_senha2.setBounds(20, 250, 140, 20);

        txt_senhaAtual2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_senhaAtual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaAtual2txt_senhaAtualActionPerformed(evt);
            }
        });
        jPanel9.add(txt_senhaAtual2);
        txt_senhaAtual2.setBounds(420, 60, 180, 20);

        manterSenha3.setBackground(new java.awt.Color(204, 204, 204));
        manterSenha3.setSelected(true);
        manterSenha3.setText("Manter senha atual");
        manterSenha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterSenha3manterSenha1ActionPerformed(evt);
            }
        });
        jPanel9.add(manterSenha3);
        manterSenha3.setBounds(420, 20, 170, 20);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setText("Nome");
        jPanel9.add(jLabel51);
        jLabel51.setBounds(70, 150, 100, 20);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_pesquisar.png"))); // NOI18N
        btnBuscar.setText("Consultar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnBuscar);
        btnBuscar.setBounds(250, 40, 110, 30);

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserir1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnInserir);
        btnInserir.setBounds(480, 300, 100, 30);

        CodFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        CodFuncionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(CodFuncionario);
        CodFuncionario.setBounds(20, 170, 40, 20);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnExcluir);
        btnExcluir.setBounds(480, 380, 100, 30);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setText("Login");
        jPanel9.add(jLabel52);
        jLabel52.setBounds(20, 190, 90, 20);
        jPanel9.add(jSeparator10);
        jSeparator10.setBounds(20, 140, 590, 10);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Senha Atual");
        jPanel9.add(jLabel53);
        jLabel53.setBounds(420, 40, 140, 20);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Código");
        jPanel9.add(jLabel54);
        jLabel54.setBounds(20, 150, 50, 20);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setText("Senha");
        jPanel9.add(jLabel55);
        jLabel55.setBounds(20, 230, 90, 20);

        txt_NovaSenha2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_NovaSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NovaSenha2txt_NovaSenhaActionPerformed(evt);
            }
        });
        jPanel9.add(txt_NovaSenha2);
        txt_NovaSenha2.setBounds(420, 100, 180, 20);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setText("Nova Senha");
        jPanel9.add(jLabel56);
        jLabel56.setBounds(420, 80, 140, 20);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissões"));
        jPanel8.setLayout(null);

        checkPerAgenda.setBackground(new java.awt.Color(204, 204, 204));
        checkPerAgenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerAgenda.setText("Agenda");
        checkPerAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerAgendajCheckBox1ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerAgenda);
        checkPerAgenda.setBounds(12, 68, 67, 23);

        checkPerProprietario.setBackground(new java.awt.Color(204, 204, 204));
        checkPerProprietario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerProprietario.setText("Proprietário");
        checkPerProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerProprietariojCheckBox3ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerProprietario);
        checkPerProprietario.setBounds(12, 16, 125, 23);

        checkPerAnimal.setBackground(new java.awt.Color(204, 204, 204));
        checkPerAnimal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerAnimal.setText("Animal");
        checkPerAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerAnimaljCheckBox8ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerAnimal);
        checkPerAnimal.setBounds(12, 42, 125, 23);

        checkPerServico.setBackground(new java.awt.Color(204, 204, 204));
        checkPerServico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerServico.setText("Serviço");
        checkPerServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerServicojCheckBox9ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerServico);
        checkPerServico.setBounds(12, 95, 65, 23);

        checkPerEstoque.setBackground(new java.awt.Color(204, 204, 204));
        checkPerEstoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerEstoque.setText("Estoque");
        checkPerEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerEstoquejCheckBox10ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerEstoque);
        checkPerEstoque.setBounds(139, 16, 71, 23);

        checkPerVenda.setBackground(new java.awt.Color(204, 204, 204));
        checkPerVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerVenda.setText("Vendas");
        checkPerVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerVendajCheckBox11ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerVenda);
        checkPerVenda.setBounds(139, 42, 65, 23);

        checkPerFinanceiro.setBackground(new java.awt.Color(204, 204, 204));
        checkPerFinanceiro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerFinanceiro.setText("Financeiro");
        checkPerFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerFinanceirojCheckBox12ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerFinanceiro);
        checkPerFinanceiro.setBounds(139, 68, 79, 23);

        checkPerProdutos.setBackground(new java.awt.Color(204, 204, 204));
        checkPerProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerProdutos.setText("Produtos");
        checkPerProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerProdutosjCheckBox13ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerProdutos);
        checkPerProdutos.setBounds(139, 95, 75, 23);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator11);
        jSeparator11.setBounds(236, 16, 2, 102);

        checkPerHistoricos.setBackground(new java.awt.Color(204, 204, 204));
        checkPerHistoricos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerHistoricos.setText("Visualizar Históricos");
        checkPerHistoricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerHistoricosjCheckBox14ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerHistoricos);
        checkPerHistoricos.setBounds(256, 16, 127, 23);

        checkPerAltera.setBackground(new java.awt.Color(204, 204, 204));
        checkPerAltera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerAltera.setText("Alterar Dados");
        checkPerAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerAlterajCheckBox15ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerAltera);
        checkPerAltera.setBounds(256, 42, 99, 23);

        checkPerExclui.setBackground(new java.awt.Color(204, 204, 204));
        checkPerExclui.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPerExclui.setText("Excluir Dados");
        checkPerExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPerExcluijCheckBox16ActionPerformed(evt);
            }
        });
        jPanel8.add(checkPerExclui);
        checkPerExclui.setBounds(256, 68, 97, 23);

        jPanel9.add(jPanel8);
        jPanel8.setBounds(20, 280, 410, 140);

        jPanel6.add(jPanel9);
        jPanel9.setBounds(10, 20, 610, 430);

        jTabbedPane1.addTab("Vendas", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackupActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void btnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar1ActionPerformed
        flag = 0;
        int codigo;

        String nome, login, senhaNova, senhaAtual, permissao = "", senha;
        codigo = Integer.parseInt(txt_login2.getText());
        nome = txt_nome2.getText();
        login = txt_login2.getText();
        senhaNova = txt_NovaSenha2.getText();

        if (manterSenha3.isSelected()) {
            senha = sen;
        } else {

            senha = senhaNova;
        }
        senhaAtual = txt_senhaAtual2.getText();

        if (checkPerProprietario.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }

        if (checkPerAnimal.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerAgenda.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerServico.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerEstoque.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerVenda.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerFinanceiro.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerProdutos.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerHistoricos.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerAltera.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerExclui.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (valida()) {

            if (Integer.parseInt(ba.abreUsuarios()) + 1 != codigo) {

                if (ba.verificaSenha(codigo, senhaAtual) || manterSenha3.isSelected()) {
                    ba.atualizaUsuario(codigo, nome, login, senha, permissao);
                    txt_nome2.setText("");
                    txt_senha2.setText("");
                    txt_login2.setText("");
                    

                    checkPerProprietario.setSelected(false);
                    checkPerAnimal.setSelected(false);
                    checkPerAgenda.setSelected(false);
                    checkPerServico.setSelected(false);
                    checkPerEstoque.setSelected(false);
                    checkPerVenda.setSelected(false);
                    checkPerFinanceiro.setSelected(false);
                    checkPerProdutos.setSelected(false);
                    checkPerHistoricos.setSelected(false);
                    checkPerAltera.setSelected(false);
                    checkPerExclui.setSelected(false);
                } else {
                    JOptionPane.showMessageDialog(null, "senha Atual incorreta para o login " + login);
                }
            } else {
                JOptionPane.showMessageDialog(null, "O código do usuario não existe,"
                        + " para alterar um usuario faça uma busca.");
            }
        }
    }//GEN-LAST:event_btnAlterar1ActionPerformed

    private void txt_login2txt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_login2txt_loginMouseClicked
        int cod = Integer.parseInt(ba.abreUsuarios()) + 1;
        CodFuncionario.setText(cod + "");
    }//GEN-LAST:event_txt_login2txt_loginMouseClicked

    private void txt_login2txt_loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_login2txt_loginMouseReleased

    }//GEN-LAST:event_txt_login2txt_loginMouseReleased

    private void txt_login2txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login2txt_loginActionPerformed

    }//GEN-LAST:event_txt_login2txt_loginActionPerformed

    private void txt_senha2txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senha2txt_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senha2txt_senhaActionPerformed

    private void txt_senhaAtual2txt_senhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaAtual2txt_senhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaAtual2txt_senhaAtualActionPerformed

    private void manterSenha3manterSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterSenha3manterSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manterSenha3manterSenha1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        ResultSet rs;
        String login = txt_BuscaLogin2.getText();
        String permissao;

        rs = ba.buscaUsuario(login);
        try {
            if (ba.buscaUsuario(login) != null) {
                txt_nome2.setText(rs.getString("nome"));
                CodFuncionario.setText(rs.getString("codigo"));
                sen = rs.getString("senha");
                permissao = rs.getString("permissao");

                if (checkPerProprietario.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }

                if (checkPerAnimal.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerAgenda.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerServico.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerEstoque.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerVenda.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerFinanceiro.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerProdutos.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerHistoricos.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerAltera.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }
                if (checkPerExclui.isSelected()) {
                    permissao += "1";
                } else {
                    permissao += "0";
                }

                txt_login2.setText(txt_BuscaLogin2.getText());

            } else {
                JOptionPane.showMessageDialog(null, "não encontrado");
                txt_nome2.setText("");
                txt_login2.setText("");
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserir1ActionPerformed
        flag = 1;
        int codigo;
        String nome, login, senha, permissao = "";
        codigo = Integer.parseInt(ba.abreUsuarios()) + 1;
        nome = txt_nome2.getText();
        login = txt_login2.getText();
        senha = txt_senha2.getText();
        if (checkPerProprietario.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }

        if (checkPerAnimal.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerAgenda.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerServico.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerEstoque.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerVenda.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerFinanceiro.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerProdutos.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerHistoricos.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerAltera.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }
        if (checkPerExclui.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }

        if (valida()) {

            if (ba.gravaUsuario(codigo, nome, login, senha, permissao)) {

                txt_nome2.setText("");
                txt_senha2.setText("");
                txt_login2.setText("");

                checkPerProprietario.setSelected(false);
                checkPerAnimal.setSelected(false);
                checkPerAgenda.setSelected(false);
                checkPerServico.setSelected(false);
                checkPerEstoque.setSelected(false);
                checkPerVenda.setSelected(false);
                checkPerFinanceiro.setSelected(false);
                checkPerProdutos.setSelected(false);
                checkPerHistoricos.setSelected(false);
                checkPerAltera.setSelected(false);
                checkPerExclui.setSelected(false);
                int cod = Integer.parseInt(ba.abreUsuarios()) + 1;
                CodFuncionario.setText(cod + "");
            }
        }
    }//GEN-LAST:event_btnInserir1ActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        flag = 0;
        int codigo = Integer.parseInt(CodFuncionario.getText());
        if (valida()) {

            if (Integer.parseInt(ba.abreUsuarios()) + 1 != codigo) {

                if (ba.excluiUsuario(codigo)) {
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                    txt_nome2.setText("");
                    txt_login2.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Não encontrado");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Codigo do usuario incorreto. Para excluir busque o usuário primeiro");
            }

        }
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void txt_NovaSenha2txt_NovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NovaSenha2txt_NovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NovaSenha2txt_NovaSenhaActionPerformed

    private void checkPerAgendajCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerAgendajCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerAgendajCheckBox1ActionPerformed

    private void checkPerProprietariojCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerProprietariojCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerProprietariojCheckBox3ActionPerformed

    private void checkPerAnimaljCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerAnimaljCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerAnimaljCheckBox8ActionPerformed

    private void checkPerServicojCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerServicojCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerServicojCheckBox9ActionPerformed

    private void checkPerEstoquejCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerEstoquejCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerEstoquejCheckBox10ActionPerformed

    private void checkPerVendajCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerVendajCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerVendajCheckBox11ActionPerformed

    private void checkPerFinanceirojCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerFinanceirojCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerFinanceirojCheckBox12ActionPerformed

    private void checkPerProdutosjCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerProdutosjCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerProdutosjCheckBox13ActionPerformed

    private void checkPerHistoricosjCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerHistoricosjCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerHistoricosjCheckBox14ActionPerformed

    private void checkPerAlterajCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerAlterajCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerAlterajCheckBox15ActionPerformed

    private void checkPerExcluijCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerExcluijCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPerExcluijCheckBox16ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodFuncionario;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JCheckBox checkPerAgenda;
    private javax.swing.JCheckBox checkPerAltera;
    private javax.swing.JCheckBox checkPerAnimal;
    private javax.swing.JCheckBox checkPerEstoque;
    private javax.swing.JCheckBox checkPerExclui;
    private javax.swing.JCheckBox checkPerFinanceiro;
    private javax.swing.JCheckBox checkPerHistoricos;
    private javax.swing.JCheckBox checkPerProdutos;
    private javax.swing.JCheckBox checkPerProprietario;
    private javax.swing.JCheckBox checkPerServico;
    private javax.swing.JCheckBox checkPerVenda;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JCheckBox manterSenha3;
    private javax.swing.JTextField txt_BuscaLogin2;
    private javax.swing.JPasswordField txt_NovaSenha2;
    private javax.swing.JTextField txt_login2;
    private javax.swing.JTextField txt_nome2;
    private javax.swing.JPasswordField txt_senha2;
    private javax.swing.JPasswordField txt_senhaAtual2;
    // End of variables declaration//GEN-END:variables
}
