/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Rafael
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form ProdutosConsultar
     */
    public Produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton20 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnProprietario = new javax.swing.JButton();
        btnAnimal = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnConfiguracoes = new javax.swing.JButton();
        btnAjuda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(204, 204, 204));

        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setText("Bem vindo Fulano!");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(833, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 960, 20);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.setLayout(null);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_pesquisar.png"))); // NOI18N
        jButton10.setText("Consultar");
        jButton10.setToolTipText("");
        jButton10.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(397, 52, 110, 32);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButton12.setText("Inserir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jButton12.setBounds(517, 53, 101, 30);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel6.add(jTextField2);
        jTextField2.setBounds(11, 57, 165, 21);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel6.add(jTextField1);
        jTextField1.setBounds(186, 57, 201, 21);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("EAN");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(11, 31, 24, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Produto");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(186, 31, 51, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Consultar Produtos");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(278, 1, 120, 15);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir Produtos"));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Validade");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(375, 150, 61, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Produto");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(16, 27, 51, 15);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(16, 50, 251, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("EAN");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(16, 91, 24, 15);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(16, 112, 134, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NCM");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(168, 91, 27, 15);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(168, 112, 154, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Categoria");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(16, 150, 59, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Fornecedor");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(160, 150, 68, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Observação");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(16, 362, 70, 15);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(16, 388, 515, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Marca");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(303, 27, 36, 15);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(303, 48, 154, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medicamentos", "Estética", "Materiais Cirúrgicos", "Materiais Descartáveis" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(16, 171, 120, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Farma Pet", "PetCLean", "Cirur-cão", "Pet Embalagens" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(160, 171, 120, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "KG", "PT", "LT", " " }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(298, 171, 50, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Unidade");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(298, 150, 59, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Valor Unidade");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(114, 212, 84, 15);
        jPanel2.add(jTextField10);
        jTextField10.setBounds(114, 233, 84, 20);
        jPanel2.add(jTextField11);
        jTextField11.setBounds(16, 233, 80, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Estoque Min.");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(16, 212, 80, 15);
        jPanel2.add(jTextField12);
        jTextField12.setBounds(216, 233, 84, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Lucro(%)");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(216, 212, 84, 15);
        jPanel2.add(jTextField13);
        jTextField13.setBounds(318, 233, 84, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Valor Venda");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(318, 212, 84, 15);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(375, 171, 87, 20);

        jPanel6.add(jPanel2);
        jPanel2.setBounds(11, 95, 0, 340);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filefind.png"))); // NOI18N
        jButton20.setText("Histórico");
        jPanel6.add(jButton20);
        jButton20.setBounds(196, 446, 105, 35);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apply.png"))); // NOI18N
        jButton15.setText("Salvar");
        jPanel6.add(jButton15);
        jButton15.setBounds(311, 446, 93, 35);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_excluir.png"))); // NOI18N
        jButton16.setText("Cancelar");
        jPanel6.add(jButton16);
        jButton16.setBounds(519, 446, 105, 35);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        jButton21.setText("Excluir");
        jPanel6.add(jButton21);
        jButton21.setBounds(414, 446, 95, 35);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir Produtos"));
        jPanel3.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Validade");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(375, 150, 61, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Produto");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(16, 27, 51, 15);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(16, 50, 251, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("EAN");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(16, 91, 24, 15);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(16, 112, 134, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("NCM");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(168, 91, 27, 15);
        jPanel3.add(jTextField14);
        jTextField14.setBounds(168, 112, 154, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Categoria");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(16, 150, 59, 15);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Fornecedor");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(160, 150, 68, 15);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Observação");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(16, 259, 70, 15);
        jPanel3.add(jTextField15);
        jTextField15.setBounds(16, 285, 515, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Marca");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(303, 27, 36, 15);
        jPanel3.add(jTextField16);
        jTextField16.setBounds(303, 48, 154, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medicamentos", "Estética", "Materiais Cirúrgicos", "Materiais Descartáveis" }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(16, 171, 120, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Farma Pet", "PetCLean", "Cirur-cão", "Pet Embalagens" }));
        jPanel3.add(jComboBox5);
        jComboBox5.setBounds(160, 171, 120, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "KG", "PT", "LT", " " }));
        jPanel3.add(jComboBox6);
        jComboBox6.setBounds(298, 171, 50, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Unidade");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(298, 150, 59, 15);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Valor Unidade");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(114, 212, 84, 15);
        jPanel3.add(jTextField17);
        jTextField17.setBounds(114, 233, 84, 20);
        jPanel3.add(jTextField18);
        jTextField18.setBounds(16, 233, 80, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Estoque Min.");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(16, 212, 80, 15);
        jPanel3.add(jTextField19);
        jTextField19.setBounds(216, 233, 84, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Lucro(%)");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(216, 212, 84, 15);
        jPanel3.add(jTextField20);
        jTextField20.setBounds(318, 233, 84, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Valor Venda");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(318, 212, 84, 15);
        jPanel3.add(jDateChooser2);
        jDateChooser2.setBounds(370, 170, 87, 20);

        jPanel6.add(jPanel3);
        jPanel3.setBounds(10, 90, 610, 330);

        jTabbedPane1.addTab("Produto", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 640, 530);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/suporte.png"))); // NOI18N
        jButton22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton22.setContentAreaFilled(false);
        getContentPane().add(jButton22);
        jButton22.setBounds(10, 550, 100, 50);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jButton23.setContentAreaFilled(false);
        getContentPane().add(jButton23);
        jButton23.setBounds(110, 550, 100, 50);

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_inicio1.png"))); // NOI18N
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(700, 40, 70, 80);

        btnProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_proprietario1.png"))); // NOI18N
        btnProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProprietarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnProprietario);
        btnProprietario.setBounds(770, 40, 70, 80);

        btnAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_animal1.png"))); // NOI18N
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnimal);
        btnAnimal.setBounds(840, 40, 70, 80);

        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_estoque1.png"))); // NOI18N
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstoque);
        btnEstoque.setBounds(840, 120, 70, 80);

        btnServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_serviço1.png"))); // NOI18N
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnServicos);
        btnServicos.setBounds(770, 120, 70, 80);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones_agenda1.png"))); // NOI18N
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgenda);
        btnAgenda.setBounds(700, 120, 70, 80);

        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones_vendas1.png"))); // NOI18N
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVendas);
        btnVendas.setBounds(700, 200, 70, 80);

        btnFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_financeiro1.png"))); // NOI18N
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinanceiro);
        btnFinanceiro.setBounds(770, 200, 70, 80);

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones_produtos1.png"))); // NOI18N
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProdutos);
        btnProdutos.setBounds(840, 200, 70, 80);

        btnConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones_configurações1.png"))); // NOI18N
        btnConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracoesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracoes);
        btnConfiguracoes.setBounds(770, 280, 70, 80);

        btnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_ajuda1.png"))); // NOI18N
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjuda);
        btnAjuda.setBounds(700, 280, 70, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo telas.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 610);

        setSize(new java.awt.Dimension(974, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        Inicial ini = new Inicial();
        this.setVisible(false);
        ini.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProprietarioActionPerformed
        // TODO add your handling code here:
        Proprietario prop = new Proprietario();
        this.setVisible(false);
        prop.setVisible(true);
    }//GEN-LAST:event_btnProprietarioActionPerformed

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalActionPerformed
        // TODO add your handling code here:
        Animal ani = new Animal();
        this.setVisible(false);
        ani.setVisible(true);
    }//GEN-LAST:event_btnAnimalActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        Estoque est = new Estoque();
        this.setVisible(false);
        est.setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        // TODO add your handling code here:
        Servicos ser = new Servicos();
        this.setVisible(false);
        ser.setVisible(true);
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        // TODO add your handling code here:
        Agenda agen = new Agenda();
        this.setVisible(false);
        agen.setVisible(true);
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        Vendas ven = new Vendas();
        this.setVisible(false);
        ven.setVisible(true);
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        // TODO add your handling code here:
        FinanceiroPagar fin = new FinanceiroPagar();
        this.setVisible(false);
        fin.setVisible(true);
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracoesActionPerformed
        Configuracoes conf = new Configuracoes();
        this.setVisible(false);
        conf.setVisible(true);
    }//GEN-LAST:event_btnConfiguracoesActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // TODO add your handling code here:
        Ajuda aju = new Ajuda();
        this.setVisible(false);
        aju.setVisible(true);
    }//GEN-LAST:event_btnAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnAnimal;
    private javax.swing.JButton btnConfiguracoes;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnProprietario;
    private javax.swing.JButton btnServicos;
    private javax.swing.JButton btnVendas;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
